import { useEffect, useState } from 'react';
import { education, experience, metrics, profile, projects, skills } from './data/portfolio';
import { PortfolioAssistant } from './components/PortfolioAssistant';
import './styles.css';
const nav=['about','projects','skills','experience','education'];
export default function App(){
 const [dark,setDark]=useState(()=>localStorage.getItem('theme')==='dark'); const [menu,setMenu]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('theme',dark?'dark':'light')},[dark]);
 return <>
  <a className="skip-link" href="#main-content">Skip to main content</a>
  <header className="nav"><a className="brand" href="#top">PG</a><button className="menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(v=>!v)}>☰</button><nav className={menu?'open':''} aria-label="Primary navigation">{nav.map(x=><a key={x} href={`#${x}`} onClick={()=>setMenu(false)}>{x[0].toUpperCase()+x.slice(1)}</a>)}</nav><div className="nav-actions"><button className="icon" aria-label={`Switch to ${dark?'light':'dark'} mode`} onClick={()=>setDark(v=>!v)}>{dark?'☀':'☾'}</button><a className="button small" href={`mailto:${profile.email}`}>Get in touch</a></div></header>
  <main id="main-content">
   <section id="top" className="hero shell"><div><span className="eyebrow">{profile.title}</span><h1>{profile.name}</h1><h2>{profile.headline}</h2><p>{profile.summary}</p><div className="actions"><a className="button" href="#projects">View projects</a><a className="button secondary" href="Pawan-Ghimire-Resume.pdf" download>Download résumé</a><a className="button ghost" href={`mailto:${profile.email}`}>Contact me</a></div><div className="tags">{['Java 8/11/17','Spring Boot','Microservices','Kafka','GCP & AWS','React','AI-assisted engineering'].map(t=><span key={t}>{t}</span>)}</div></div><div className="portrait-card"><img src="pawan-ghimire.jpg" alt="Pawan Ghimire"/><div><strong>{profile.location}</strong><span>Open to discussing opportunities</span></div></div></section>
   <section id="about" className="section alt"><div className="shell"><span className="eyebrow">About</span><h2>Engineering with measurable outcomes</h2><p className="lead">Senior Software Engineer with a strong background in Java, Spring Boot microservices, REST APIs, cloud-native systems, modern frontend delivery, and automated quality. Recent work includes POS analytics and device-health platforms at Walmart Global Tech, modernization at Paychex, and customer-facing software at WorldLink Communications.</p><div className="metrics">{metrics.map(m=><article key={m.label}><strong>{m.value}</strong><span>{m.label}</span></article>)}</div></div></section>
   <section id="projects" className="section"><div className="shell"><span className="eyebrow">Selected work</span><h2>Representative case studies</h2><div className="cards">{projects.map((p,i)=><article className="project" key={p.title}><span className="number">0{i+1}</span><h3>{p.title}</h3><h4>{p.subtitle}</h4><p>{p.description}</p><strong className="result">{p.result}</strong><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></div></section>
   <section id="skills" className="section alt"><div className="shell"><span className="eyebrow">Technical toolkit</span><h2>Core skills</h2><div className="skill-grid">{Object.entries(skills).map(([group,items])=><article key={group}><h3>{group}</h3><div className="tags">{items.map(x=><span key={x}>{x}</span>)}</div></article>)}</div></div></section>
   <section id="experience" className="section"><div className="shell"><span className="eyebrow">Experience</span><h2>Professional journey</h2><div className="timeline">{experience.map(e=><article key={e.company}><div className="dot"/><div className="job-head"><div><span>{e.company}</span><h3>{e.role}</h3></div><small>{e.period} · {e.location}</small></div><ul>{e.points.map(p=><li key={p}>{p}</li>)}</ul></article>)}</div></div></section>
   <section id="education" className="section alt"><div className="shell"><span className="eyebrow">Education</span><h2>Academic background</h2><div className="education">{education.map(e=><article key={e.school}><span>{e.year}</span><h3>{e.school}</h3><p>{e.degree}</p></article>)}</div></div></section>
   <section className="cta"><div className="shell"><div><span className="eyebrow">Let’s connect</span><h2>Building a platform that needs to scale?</h2><p>Reach out to discuss Java backend engineering, cloud modernization, performance improvements, automated quality, or AI-enabled development.</p></div><div className="actions"><a className="button light" href={`mailto:${profile.email}`}>Email Pawan</a><a className="button outline-light" href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a></div></div></section>
  </main>
  <footer><div className="shell"><span>© {new Date().getFullYear()} Pawan Ghimire</span><div><a href={`mailto:${profile.email}`}>Email</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href="Pawan-Ghimire-Resume.pdf" download>Résumé</a></div></div></footer>
  <PortfolioAssistant/>
 </>;
}
