import { useEffect, useState } from 'react';
import { education, experience, metrics, profile, projects, skills } from './data/portfolio';
import { PortfolioAssistant } from './components/PortfolioAssistant';
import './styles.css';
const nav=['about','projects','skills','experience','education'];
const flow=['POS telemetry','Kafka','Spring Boot','BigQuery / Cache','React / Grafana'];
export default function App(){
 const [dark,setDark]=useState(()=>localStorage.getItem('theme')==='dark'); const [menu,setMenu]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('theme',dark?'dark':'light')},[dark]);
 return <>
 <a className="skip-link" href="#main-content">Skip to main content</a>
 <header className="nav"><a className="brand" href="#top">PG</a><button className="menu" aria-label="Toggle navigation" onClick={()=>setMenu(v=>!v)}>☰</button><nav className={menu?'open':''}>{nav.map(x=><a key={x} href={'#'+x} onClick={()=>setMenu(false)}>{x[0].toUpperCase()+x.slice(1)}</a>)}</nav><div className="nav-actions"><button className="icon" aria-label="Toggle theme" onClick={()=>setDark(v=>!v)}>{dark?'☀':'☾'}</button><a className="button small" href={'mailto:'+profile.email}>Get in touch</a></div></header>
 <main id="main-content">
  <section id="top" className="hero shell"><div className="hero-copy"><span className="eyebrow">{profile.title}</span><h1>{profile.name}</h1><h2>{profile.headline}</h2><p>{profile.summary}</p><div className="actions"><a className="button" href="#projects">View selected work</a><a className="button secondary" href="Pawan-Ghimire-Resume.pdf" download>Download résumé</a></div><div className="hero-stack">{['Java 17','Spring Boot','Distributed Systems','Kafka','GCP','React','AI & Agentic Systems'].map(t=><span key={t}>{t}</span>)}</div></div><div className="portrait-card"><img src="pawan-ghimire.jpg" alt="Pawan Ghimire"/><div><strong>Dallas, Texas</strong><span>Senior Software Engineer · Open to opportunities</span></div></div></section>
  <section id="about" className="section subtle"><div className="shell"><div className="section-heading"><span className="eyebrow">About</span><h2>Engineering reliable systems at scale</h2><p>I specialize in backend and distributed systems, with experience across cloud infrastructure, modern web applications, production reliability, and AI-enabled engineering.</p></div><div className="metrics">{metrics.map(m=><article key={m.label}><strong>{m.value}</strong><span>{m.label}</span></article>)}</div></div></section>
  <section id="projects" className="section"><div className="shell"><div className="section-heading"><span className="eyebrow">Selected work</span><h2>Projects and impact</h2><p>A selection of systems I have helped design, build, optimize, and operate in production.</p></div><div className="projects">{projects.map((p,i)=><article className="project" key={p.title}><div className="project-top"><span className="project-number">0{i+1}</span><span className="project-subtitle">{p.subtitle}</span></div><h3>{p.title}</h3><p>{p.description}</p><div className="result">{p.result}</div><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div>{i===0&&<div className="architecture"><small>High-level architecture</small><div>{flow.map((x,j)=><div key={x}><span>{x}</span>{j<flow.length-1&&<b>→</b>}</div>)}</div></div>}</article>)}</div></div></section>
  <section id="skills" className="section subtle"><div className="shell"><div className="section-heading"><span className="eyebrow">Technical expertise</span><h2>Core technologies</h2></div><div className="skill-grid">{Object.entries(skills).map(([group,items])=><article key={group}><h3>{group}</h3><div className="tags">{items.map(x=><span key={x}>{x}</span>)}</div></article>)}</div></div></section>
  <section id="experience" className="section"><div className="shell"><div className="section-heading"><span className="eyebrow">Experience</span><h2>Professional experience</h2></div><div className="timeline">{experience.map(e=><article key={e.company}><div className="job-head"><div><h3>{e.role}</h3><strong>{e.company}</strong></div><div className="job-meta">{e.period}<br/>{e.location}</div></div><ul>{e.points.map(p=><li key={p}>{p}</li>)}</ul></article>)}</div></div></section>
  <section id="education" className="section subtle"><div className="shell"><div className="section-heading"><span className="eyebrow">Education</span><h2>Academic background</h2></div><div className="education">{education.map(e=><article key={e.school}><span>{e.year}</span><h3>{e.school}</h3><p>{e.degree}</p></article>)}</div></div></section>
  <section className="cta"><div className="shell"><div><span className="eyebrow">Contact</span><h2>Interested in working together?</h2><p>I’m open to senior software engineering opportunities focused on distributed systems, cloud platforms, event-driven architecture, and AI-enabled products.</p></div><div className="actions"><a className="button light" href={'mailto:'+profile.email}>Email Pawan</a><a className="button outline" href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a></div></div></section>
 </main>
 <footer><div className="shell"><span>© {new Date().getFullYear()} Pawan Ghimire</span><div><a href={'mailto:'+profile.email}>Email</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href="Pawan-Ghimire-Resume.pdf" download>Résumé</a></div></div></footer>
 <PortfolioAssistant/>
 </>;
}