import { useEffect, useState } from 'react';
import { education, experience, metrics, profile, projects, skills } from './data/portfolio';
import { PortfolioAssistant } from './components/PortfolioAssistant';
import './styles.css';
const nav=['about','projects','skills','experience','education'];
const flow=['150K+ POS devices','Kafka event stream','Spring Boot services','BigQuery + cache','React + Grafana'];
export default function App(){
 const [dark,setDark]=useState(()=>localStorage.getItem('theme')==='dark'); const [menu,setMenu]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('theme',dark?'dark':'light')},[dark]);
 return <>
  <a className="skip-link" href="#main-content">Skip to main content</a>
  <header className="nav"><a className="brand" href="#top"><span>PG</span></a><button className="menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(v=>!v)}>☰</button><nav className={menu?'open':''}>{nav.map(x=><a key={x} href={'#'+x} onClick={()=>setMenu(false)}>{x[0].toUpperCase()+x.slice(1)}</a>)}</nav><div className="nav-actions"><button className="icon" aria-label="Toggle theme" onClick={()=>setDark(v=>!v)}>{dark?'☀':'☾'}</button><a className="button small" href={'mailto:'+profile.email}>Let’s talk <span>↗</span></a></div></header>
  <main id="main-content">
   <section id="top" className="hero shell"><div className="hero-copy"><div className="availability"><i/> Available for senior engineering opportunities</div><span className="eyebrow">{profile.title} · Dallas, Texas</span><h1><span>Pawan</span><br/>Ghimire</h1><h2>{profile.headline}</h2><p>{profile.summary}</p><div className="actions"><a className="button" href="#projects">Explore my work <span>↓</span></a><a className="button secondary" href="Pawan-Ghimire-Resume.pdf" download>Résumé ↗</a></div><div className="hero-stack">{['Java 17','Spring Boot','Kafka','GCP','React','AI / Agents'].map(t=><span key={t}>{t}</span>)}</div></div><div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="portrait-card"><div className="portrait-glow"/><img src="pawan-ghimire.jpg" alt="Pawan Ghimire"/><div className="portrait-meta"><span>Currently exploring</span><strong>Distributed systems × AI</strong></div></div><div className="float-card float-one"><b>7+</b><span>Years building</span></div><div className="float-card float-two"><b>150K+</b><span>Devices at scale</span></div></div></section>
   <div className="marquee"><div>JAVA 17 <i>✦</i> DISTRIBUTED SYSTEMS <i>✦</i> KAFKA <i>✦</i> GCP <i>✦</i> SPRING BOOT <i>✦</i> REACT <i>✦</i> AGENTIC AI <i>✦</i></div></div>
   <section id="about" className="section"><div className="shell split-heading"><div><span className="eyebrow">01 / About</span><h2>I turn complex systems into <em>reliable products.</em></h2></div><p className="lead">I work where backend engineering, distributed systems, cloud infrastructure, and product experience meet. My focus is simple: build systems that stay fast, observable, secure, and useful as they scale.</p></div><div className="shell metrics">{metrics.map(m=><article key={m.label}><strong>{m.value}</strong><span>{m.label}</span></article>)}</div></section>
   <section id="projects" className="section projects-section"><div className="shell"><div className="section-title"><span className="eyebrow">02 / Selected work</span><h2>Engineering that ships.<br/><em>Impact you can measure.</em></h2></div><div className="project-list">{projects.map((p,i)=><article className={'project project-'+i} key={p.title}><div className="project-index">0{i+1}</div><div className="project-main"><span className="project-kicker">{p.subtitle}</span><h3>{p.title}</h3><p>{p.description}</p><strong className="result">{p.result}</strong><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div>{i===0&&<div className="architecture"><span>System flow</span><div>{flow.map((x,j)=><div key={x}><b>{x}</b>{j<flow.length-1&&<i>→</i>}</div>)}</div></div>}</div></article>)}</div></div></section>
   <section id="skills" className="section skills-section"><div className="shell"><div className="section-title"><span className="eyebrow">03 / Toolkit</span><h2>Deep backend roots.<br/><em>Full-stack range.</em></h2></div><div className="skill-grid">{Object.entries(skills).map(([group,items],i)=><article key={group}><span>0{i+1}</span><h3>{group}</h3><div className="tags">{items.map(x=><b key={x}>{x}</b>)}</div></article>)}</div></div></section>
   <section id="experience" className="section"><div className="shell"><div className="section-title"><span className="eyebrow">04 / Experience</span><h2>Built in production.<br/><em>Learned at scale.</em></h2></div><div className="timeline">{experience.map((e,i)=><article key={e.company}><div className="year">0{i+1}</div><div className="job-head"><div><span>{e.company}</span><h3>{e.role}</h3></div><small>{e.period}<br/>{e.location}</small></div><ul>{e.points.map(p=><li key={p}>{p}</li>)}</ul></article>)}</div></div></section>
   <section id="education" className="section education-section"><div className="shell"><span className="eyebrow">05 / Education</span><div className="education">{education.map(e=><article key={e.school}><span>{e.year}</span><h3>{e.school}</h3><p>{e.degree}</p></article>)}</div></div></section>
   <section className="cta"><div className="shell"><span className="eyebrow">Have a hard problem?</span><h2>Let’s build something<br/><em>that matters.</em></h2><p>Distributed systems, cloud platforms, event-driven architecture, or AI-enabled products — I’m always interested in ambitious engineering work.</p><div className="actions"><a className="button light" href={'mailto:'+profile.email}>Start a conversation ↗</a><a className="text-link" href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></section>
  </main>
  <footer><div className="shell"><strong>PG</strong><span>© {new Date().getFullYear()} Pawan Ghimire</span><div><a href={'mailto:'+profile.email}>Email</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href="Pawan-Ghimire-Resume.pdf" download>Résumé</a></div></div></footer>
  <PortfolioAssistant/>
 </>;
}